services:
  api:
    build: ./api
    ports:
      - 3000:3000
    env_file:
      - ./api/.env.dev
    volumes:
      - ./api/src:/app/src
    
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/src
    env_file:
      - ./client/.env.dev

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: mini-auth
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
